### ISSUE TITLE
 'Move to Trash' Button Behavior Issue in 'My Tutorials' Page"

### ISSUE THREAD

**Issue by SURAJ-SHARMA27** [scorelab/Codelabz#935]
**Describe the bug**
When navigating to the "My Tutorials" page and creating a tutorial, clicking the "Move to Trash" button doesn't behave as expected.

**To Reproduce**
1. Log in to the application.
2. Navigate to the "My Tutorials" page.
3. Create a tutorial.
4. Click the "Move to Trash" button.

**Expected behavior**

- If the tutorial is already published, the "Move to Trash" button should be disabled and not clickable.
- If the tutorial is unpublished, clicking the "Move to Trash" button should trigger a modal dialog to confirm deletion.
- Upon confirming deletion in the modal, the user should be redirected to the tutorial homepage or an appropriate page.

**Screenshots**

https://github.com/scorelab/Codelabz/assets/90304648/342f939c-90c7-4159-943f-8e575c10fc5e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
This issue is affecting the user experience after creating a tutorial, and it needs to be addressed to ensure that the "Move to Trash" button behaves correctly based on the tutorial's publishing status.

**Comment by SURAJ-SHARMA27** [comment]
@shivareddy6 @ABHISHEK-PANDEY2  @Sarfraz-droid @Maahi10001 can you assign me this issue? I have fixed it.

**Comment by lokeshsingh3721** [comment]
this issue is not resolved yet ..can you please assign this to me.

https://github.com/scorelab/Codelabz/assets/71646466/1672adf4-9a45-4f4b-83d5-d049135b1c12

**Comment by SURAJ-SHARMA27** [comment]
Hey @lokeshsingh3721 , I have already addressed the issue in PR #938
